[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = [
  'py37',
  'py38',
  'py39',
]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
]
addopts = "--doctest-modules --mpl"


[tool.mypy]
python_version = "3.6"
