name: CI
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [
          "3.6",
          "3.7",
          "3.8",
          "3.9",
          #"3.10-dev"
        ]
        include:
          # only test oldest and most recent Python on other platforms
          - os: macos-latest
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.6'
          - os: windows-latest
            python-version: '3.9'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: |
        python3 -m pip install --upgrade pip
        # install wheel for experimental job (Python 3.10)
        python3 -m pip install --upgrade wheel
        python3 -m pip install --pre .[dev]
    - name: Run test suite
      run: pytest --mpl-results-path=test_results
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results
        path: test_results/

  minimal-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Setup package
      run: |
        python3 -m pip install --upgrade pip
        python tests/scripts/hardpin_minimal_dependencies.py
        python3 -m pip install -e .[dev]
    - name: Run test suite
      run: |
        export MPLBACKEND=Agg
        pytest --mpl-results-path=test_results
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results
        path: test_results/
